# Basic set up

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"

  # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--
  - package-ecosystem: "nuget"
    directories:
      - "/"
      - "/src/Giraffe/"
      - "/tests/Giraffe.Tests/"
    schedule:
      interval: "weekly"
